version: '3'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-master-data:/data
    ports:
      - '6379:6379'
    networks:
      redis-net:
        ipv4_address: 172.21.0.3

  slave1:
    image: redis:latest
    container_name: slave1
    command: ['redis-server', '--replicaof', 'redis-master', '6379']
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-slave-1-data:/data
    ports:
      - '6380:6379'
    depends_on:
      - redis-master
    networks:
      redis-net:
        ipv4_address: 172.21.0.4

  slave2:
    image: redis:latest
    container_name: slave2
    command: ['redis-server', '--replicaof', 'redis-master', '6379']
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-slave-2-data:/data
    ports:
      - '6381:6379'
    depends_on:
      - redis-master
    networks:
      redis-net:
        ipv4_address: 172.21.0.5

  sentinel-1:
    image: redis:latest
    container_name: sentinel-1
    hostname: sentinel-1
    command: >
      sh -c 'echo "sentinel monitor mymaster 172.21.0.3 6379 2" >> /etc/sentinel.conf &&
          redis-sentinel /etc/sentinel.conf'
    volumes:
      - ./sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
    ports:
      - '26379:26379'
    environment:
      - MASTER_IP=172.21.0.3
    networks:
      redis-net:
        ipv4_address: 172.21.0.6

  sentinel-2:
    image: redis:latest
    container_name: sentinel-2
    hostname: sentinel-2
    command: >
      sh -c 'echo "sentinel monitor mymaster 172.21.0.3 6379 2" >> /etc/sentinel.conf &&
          redis-sentinel /etc/sentinel.conf'
    volumes:
      - ./sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
    ports:
      - '26380:26379'
    environment:
      - MASTER_IP=172.21.0.3
    networks:
      redis-net:
        ipv4_address: 172.21.0.7

  sentinel-3:
    image: redis:latest
    container_name: sentinel-3
    hostname: sentinel-3
    command: >
      sh -c 'echo "sentinel monitor mymaster 172.21.0.3 6379 2" >> /etc/sentinel.conf &&
          redis-sentinel /etc/sentinel.conf'
    volumes:
      - ./sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
    ports:
      - '26381:26379'
    environment:
      - MASTER_IP=172.21.0.3
    networks:
      redis-net:
        ipv4_address: 172.21.0.8

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - '5540:5540'
    networks:
      redis-net:
        ipv4_address: 172.21.0.9

volumes:
  redis-master-data:
  redisinsight-data:
  redis-slave-1-data:
  redis-slave-2-data:
  redis-slave-3-data:

networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
